music/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'music'

urlpatterns = [
    #/music/
    path('', views.IndexView.as_view(), name='index'),
    
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    
    #/music/album_id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    #/music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    
    #/music/album_id/2/
    url(r'^(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    
    #/music/album_id/2/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
       
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views 
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name ='home'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Album(models.Model):
    artist = models.CharField(max_length=500)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=500)
    album_logo = models.FileField()
    
    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})
    
    def __str__(self):
        return self.album_title + '-' + self.artist
    

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=500)
    artist = models.CharField(max_length=500)
    song_title = models.CharField(max_length=500)
    is_favorite = models.BooleanField(default=False)
    
    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        
        

music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Album, Song
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name= 'all_albums'
    def get_queryset(self):
        return Album.objects.all()
    
class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'
    
class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']
    
class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')
    
class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'
    
    # blank form new user
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})
    
    # form data for the user
    def post(self, request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            
            #normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            
            # user objectsfor the user
            user = authenticate(username=username, password=password)
            
            if user is not None:
                
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
                
            return render(request, self.template_name, {'form':form})
        
        
            
    
    
    
    
    
    
    

music/templates/home.html
<!-- templates/home.html-->
<head>
  <Title>Login page</Title>
         
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
         
    </head> 

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <div class="alert alert-success">
  <strong>Success! You logged out.</strong>
</div>

<div class="alert alert-success">
Click here to <button type="button" class="btn btn-primary active"> <a href="{% url 'login' %}">Login</a></button>
 </div>   

{% endif %}
{% endblock %}

music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block body %}

<div class="row">
    
    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
                
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    {% include 'music/form-template.html' %}
                    
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>       
                        </div>            
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>iMusic</title>
    {% load staticfiles %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<link href='https://fonts.google.com/specimen/Russo+One' rel='stylesheet' type='tect/css'>

</head>
    
<body>
    <nav class="navbar navbar-inverse"...>
        <div class="container-fluid">
        <!-- logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">iMusic</a>
        </div>
        
        
        
        <!-- items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                
                <li>
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums   
                    </a>
                </li>
                
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Song   
                    </a>
                </li>
            </ul>
            
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Music   
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout  
                    </a>
                </li>
            </ul>
            
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block body %}

    <img style="max-width:95%;border:6px double #545565;" src="{{ album.album_logo.url }}" border="10" border-color="white">
    <h1 style="color:white;"><strong>{{ album.album_title }}</strong></h1>
    <h3 style="color:white;">{{ album.artist }} </h3>

        {% csrf_token %}       


<!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    <!-- For Error Message -->
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Actions</th>
                        </tr>
                            {% for song in album.song_set.all %}
                        <tr>
                            <th>
                                {{ song.song_title }}
                        <br>
                        </th>
                            
                        </tr>
                            {% endfor %}
                        </thead>
                    </table>



{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div>
        
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        
        <div class="col-sm-10">{{ field }}</div>
        
    </div>

{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
<!-- Loads the path to static files-->

{% block body %}

        
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2-fluid">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" alt = "Generic placeholder thumbnail" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            
            {% endfor %}

{% endblock %}

music/templates/music/register.html
{% extends "music/details.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="brder-bottom mb-4">Join Today</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign UP</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="#">Sign In</a>
            </small>
            </div>
    </div>
{% endblock content %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}

{% block body %}

<div class="row">
    
    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3> Create a New Account </h3>
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    {% include 'music/form-template.html' %}
                    
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>       
                        </div>            
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block title %}All Songs{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:songs' 'all' %}">View All</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}